version: '3'

services:
    db:
        image: mongo:5
        restart: always
        ports:
            - 27117:27017
        environment:
            MONGODB_DATABASE: nest-pokemon
        volumes:
            - ./mongoDB:/data/db
